//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectofinalwebII.WSArticulo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MArticulos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MArticulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        private double costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string descripccion {
            get {
                return this.descripccionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripccionField, value) != true)) {
                    this.descripccionField = value;
                    this.RaisePropertyChanged("descripccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSArticulo.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        proyectofinalwebII.WSArticulo.AgregarResponse Agregar(proyectofinalwebII.WSArticulo.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.AgregarResponse> AgregarAsync(proyectofinalwebII.WSArticulo.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nId", ReplyAction="*")]
        int nId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> nIdAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        proyectofinalwebII.WSArticulo.GetAllResponse GetAll(proyectofinalwebII.WSArticulo.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetAllResponse> GetAllAsync(proyectofinalwebII.WSArticulo.GetAllRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getbyid", ReplyAction="*")]
        proyectofinalwebII.WSArticulo.GetbyidResponse Getbyid(proyectofinalwebII.WSArticulo.GetbyidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getbyid", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetbyidResponse> GetbyidAsync(proyectofinalwebII.WSArticulo.GetbyidRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetbyNombre", ReplyAction="*")]
        proyectofinalwebII.WSArticulo.GetbyNombreResponse GetbyNombre(proyectofinalwebII.WSArticulo.GetbyNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetbyNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetbyNombreResponse> GetbyNombreAsync(proyectofinalwebII.WSArticulo.GetbyNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetNombresResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNombres", ReplyAction="*")]
        proyectofinalwebII.WSArticulo.GetNombresResponse GetNombres(proyectofinalwebII.WSArticulo.GetNombresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNombres", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetNombresResponse> GetNombresAsync(proyectofinalwebII.WSArticulo.GetNombresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        proyectofinalwebII.WSArticulo.EliminarResponse Eliminar(proyectofinalwebII.WSArticulo.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.EliminarResponse> EliminarAsync(proyectofinalwebII.WSArticulo.EliminarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        proyectofinalwebII.WSArticulo.EditarResponse Editar(proyectofinalwebII.WSArticulo.EditarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.EditarResponse> EditarAsync(proyectofinalwebII.WSArticulo.EditarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Agregar", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.AgregarRequestBody Body;
        
        public AgregarRequest() {
        }
        
        public AgregarRequest(proyectofinalwebII.WSArticulo.AgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tipo;
        
        public AgregarRequestBody() {
        }
        
        public AgregarRequestBody(string id, string nom, double costo, string Descripcion, string Tipo) {
            this.id = id;
            this.nom = nom;
            this.costo = costo;
            this.Descripcion = Descripcion;
            this.Tipo = Tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.AgregarResponseBody Body;
        
        public AgregarResponse() {
        }
        
        public AgregarResponse(proyectofinalwebII.WSArticulo.AgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AgregarResponseBody {
        
        public AgregarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(proyectofinalwebII.WSArticulo.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(proyectofinalwebII.WSArticulo.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectofinalwebII.WSArticulo.MArticulos[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(proyectofinalwebII.WSArticulo.MArticulos[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbyidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getbyid", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetbyidRequestBody Body;
        
        public GetbyidRequest() {
        }
        
        public GetbyidRequest(proyectofinalwebII.WSArticulo.GetbyidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetbyidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetbyidRequestBody() {
        }
        
        public GetbyidRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbyidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetbyidResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetbyidResponseBody Body;
        
        public GetbyidResponse() {
        }
        
        public GetbyidResponse(proyectofinalwebII.WSArticulo.GetbyidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetbyidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectofinalwebII.WSArticulo.MArticulos GetbyidResult;
        
        public GetbyidResponseBody() {
        }
        
        public GetbyidResponseBody(proyectofinalwebII.WSArticulo.MArticulos GetbyidResult) {
            this.GetbyidResult = GetbyidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbyNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetbyNombre", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetbyNombreRequestBody Body;
        
        public GetbyNombreRequest() {
        }
        
        public GetbyNombreRequest(proyectofinalwebII.WSArticulo.GetbyNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetbyNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        public GetbyNombreRequestBody() {
        }
        
        public GetbyNombreRequestBody(string Nombre) {
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbyNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetbyNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetbyNombreResponseBody Body;
        
        public GetbyNombreResponse() {
        }
        
        public GetbyNombreResponse(proyectofinalwebII.WSArticulo.GetbyNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetbyNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectofinalwebII.WSArticulo.MArticulos GetbyNombreResult;
        
        public GetbyNombreResponseBody() {
        }
        
        public GetbyNombreResponseBody(proyectofinalwebII.WSArticulo.MArticulos GetbyNombreResult) {
            this.GetbyNombreResult = GetbyNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNombresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNombres", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetNombresRequestBody Body;
        
        public GetNombresRequest() {
        }
        
        public GetNombresRequest(proyectofinalwebII.WSArticulo.GetNombresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNombresRequestBody {
        
        public GetNombresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNombresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNombresResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.GetNombresResponseBody Body;
        
        public GetNombresResponse() {
        }
        
        public GetNombresResponse(proyectofinalwebII.WSArticulo.GetNombresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNombresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectofinalwebII.WSArticulo.ArrayOfString GetNombresResult;
        
        public GetNombresResponseBody() {
        }
        
        public GetNombresResponseBody(proyectofinalwebII.WSArticulo.ArrayOfString GetNombresResult) {
            this.GetNombresResult = GetNombresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.EliminarRequestBody Body;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(proyectofinalwebII.WSArticulo.EliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public EliminarRequestBody() {
        }
        
        public EliminarRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.EliminarResponseBody Body;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(proyectofinalwebII.WSArticulo.EliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarResponseBody {
        
        public EliminarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Editar", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.EditarRequestBody Body;
        
        public EditarRequest() {
        }
        
        public EditarRequest(proyectofinalwebII.WSArticulo.EditarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tipo;
        
        public EditarRequestBody() {
        }
        
        public EditarRequestBody(string id, string nom, double costo, string Descripcion, string Tipo) {
            this.id = id;
            this.nom = nom;
            this.costo = costo;
            this.Descripcion = Descripcion;
            this.Tipo = Tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectofinalwebII.WSArticulo.EditarResponseBody Body;
        
        public EditarResponse() {
        }
        
        public EditarResponse(proyectofinalwebII.WSArticulo.EditarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditarResponseBody {
        
        public EditarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : proyectofinalwebII.WSArticulo.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<proyectofinalwebII.WSArticulo.WebService1Soap>, proyectofinalwebII.WSArticulo.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectofinalwebII.WSArticulo.AgregarResponse proyectofinalwebII.WSArticulo.WebService1Soap.Agregar(proyectofinalwebII.WSArticulo.AgregarRequest request) {
            return base.Channel.Agregar(request);
        }
        
        public void Agregar(string id, string nom, double costo, string Descripcion, string Tipo) {
            proyectofinalwebII.WSArticulo.AgregarRequest inValue = new proyectofinalwebII.WSArticulo.AgregarRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.AgregarRequestBody();
            inValue.Body.id = id;
            inValue.Body.nom = nom;
            inValue.Body.costo = costo;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Tipo = Tipo;
            proyectofinalwebII.WSArticulo.AgregarResponse retVal = ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).Agregar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.AgregarResponse> proyectofinalwebII.WSArticulo.WebService1Soap.AgregarAsync(proyectofinalwebII.WSArticulo.AgregarRequest request) {
            return base.Channel.AgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.AgregarResponse> AgregarAsync(string id, string nom, double costo, string Descripcion, string Tipo) {
            proyectofinalwebII.WSArticulo.AgregarRequest inValue = new proyectofinalwebII.WSArticulo.AgregarRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.AgregarRequestBody();
            inValue.Body.id = id;
            inValue.Body.nom = nom;
            inValue.Body.costo = costo;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Tipo = Tipo;
            return ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).AgregarAsync(inValue);
        }
        
        public int nId() {
            return base.Channel.nId();
        }
        
        public System.Threading.Tasks.Task<int> nIdAsync() {
            return base.Channel.nIdAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectofinalwebII.WSArticulo.GetAllResponse proyectofinalwebII.WSArticulo.WebService1Soap.GetAll(proyectofinalwebII.WSArticulo.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public proyectofinalwebII.WSArticulo.MArticulos[] GetAll() {
            proyectofinalwebII.WSArticulo.GetAllRequest inValue = new proyectofinalwebII.WSArticulo.GetAllRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetAllRequestBody();
            proyectofinalwebII.WSArticulo.GetAllResponse retVal = ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetAllResponse> proyectofinalwebII.WSArticulo.WebService1Soap.GetAllAsync(proyectofinalwebII.WSArticulo.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetAllResponse> GetAllAsync() {
            proyectofinalwebII.WSArticulo.GetAllRequest inValue = new proyectofinalwebII.WSArticulo.GetAllRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetAllRequestBody();
            return ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectofinalwebII.WSArticulo.GetbyidResponse proyectofinalwebII.WSArticulo.WebService1Soap.Getbyid(proyectofinalwebII.WSArticulo.GetbyidRequest request) {
            return base.Channel.Getbyid(request);
        }
        
        public proyectofinalwebII.WSArticulo.MArticulos Getbyid(string id) {
            proyectofinalwebII.WSArticulo.GetbyidRequest inValue = new proyectofinalwebII.WSArticulo.GetbyidRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetbyidRequestBody();
            inValue.Body.id = id;
            proyectofinalwebII.WSArticulo.GetbyidResponse retVal = ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).Getbyid(inValue);
            return retVal.Body.GetbyidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetbyidResponse> proyectofinalwebII.WSArticulo.WebService1Soap.GetbyidAsync(proyectofinalwebII.WSArticulo.GetbyidRequest request) {
            return base.Channel.GetbyidAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetbyidResponse> GetbyidAsync(string id) {
            proyectofinalwebII.WSArticulo.GetbyidRequest inValue = new proyectofinalwebII.WSArticulo.GetbyidRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetbyidRequestBody();
            inValue.Body.id = id;
            return ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).GetbyidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectofinalwebII.WSArticulo.GetbyNombreResponse proyectofinalwebII.WSArticulo.WebService1Soap.GetbyNombre(proyectofinalwebII.WSArticulo.GetbyNombreRequest request) {
            return base.Channel.GetbyNombre(request);
        }
        
        public proyectofinalwebII.WSArticulo.MArticulos GetbyNombre(string Nombre) {
            proyectofinalwebII.WSArticulo.GetbyNombreRequest inValue = new proyectofinalwebII.WSArticulo.GetbyNombreRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetbyNombreRequestBody();
            inValue.Body.Nombre = Nombre;
            proyectofinalwebII.WSArticulo.GetbyNombreResponse retVal = ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).GetbyNombre(inValue);
            return retVal.Body.GetbyNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetbyNombreResponse> proyectofinalwebII.WSArticulo.WebService1Soap.GetbyNombreAsync(proyectofinalwebII.WSArticulo.GetbyNombreRequest request) {
            return base.Channel.GetbyNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetbyNombreResponse> GetbyNombreAsync(string Nombre) {
            proyectofinalwebII.WSArticulo.GetbyNombreRequest inValue = new proyectofinalwebII.WSArticulo.GetbyNombreRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetbyNombreRequestBody();
            inValue.Body.Nombre = Nombre;
            return ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).GetbyNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectofinalwebII.WSArticulo.GetNombresResponse proyectofinalwebII.WSArticulo.WebService1Soap.GetNombres(proyectofinalwebII.WSArticulo.GetNombresRequest request) {
            return base.Channel.GetNombres(request);
        }
        
        public proyectofinalwebII.WSArticulo.ArrayOfString GetNombres() {
            proyectofinalwebII.WSArticulo.GetNombresRequest inValue = new proyectofinalwebII.WSArticulo.GetNombresRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetNombresRequestBody();
            proyectofinalwebII.WSArticulo.GetNombresResponse retVal = ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).GetNombres(inValue);
            return retVal.Body.GetNombresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetNombresResponse> proyectofinalwebII.WSArticulo.WebService1Soap.GetNombresAsync(proyectofinalwebII.WSArticulo.GetNombresRequest request) {
            return base.Channel.GetNombresAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.GetNombresResponse> GetNombresAsync() {
            proyectofinalwebII.WSArticulo.GetNombresRequest inValue = new proyectofinalwebII.WSArticulo.GetNombresRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.GetNombresRequestBody();
            return ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).GetNombresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectofinalwebII.WSArticulo.EliminarResponse proyectofinalwebII.WSArticulo.WebService1Soap.Eliminar(proyectofinalwebII.WSArticulo.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public void Eliminar(string id) {
            proyectofinalwebII.WSArticulo.EliminarRequest inValue = new proyectofinalwebII.WSArticulo.EliminarRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.EliminarRequestBody();
            inValue.Body.id = id;
            proyectofinalwebII.WSArticulo.EliminarResponse retVal = ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).Eliminar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.EliminarResponse> proyectofinalwebII.WSArticulo.WebService1Soap.EliminarAsync(proyectofinalwebII.WSArticulo.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.EliminarResponse> EliminarAsync(string id) {
            proyectofinalwebII.WSArticulo.EliminarRequest inValue = new proyectofinalwebII.WSArticulo.EliminarRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.EliminarRequestBody();
            inValue.Body.id = id;
            return ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).EliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectofinalwebII.WSArticulo.EditarResponse proyectofinalwebII.WSArticulo.WebService1Soap.Editar(proyectofinalwebII.WSArticulo.EditarRequest request) {
            return base.Channel.Editar(request);
        }
        
        public void Editar(string id, string nom, double costo, string Descripcion, string Tipo) {
            proyectofinalwebII.WSArticulo.EditarRequest inValue = new proyectofinalwebII.WSArticulo.EditarRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.EditarRequestBody();
            inValue.Body.id = id;
            inValue.Body.nom = nom;
            inValue.Body.costo = costo;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Tipo = Tipo;
            proyectofinalwebII.WSArticulo.EditarResponse retVal = ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).Editar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.EditarResponse> proyectofinalwebII.WSArticulo.WebService1Soap.EditarAsync(proyectofinalwebII.WSArticulo.EditarRequest request) {
            return base.Channel.EditarAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectofinalwebII.WSArticulo.EditarResponse> EditarAsync(string id, string nom, double costo, string Descripcion, string Tipo) {
            proyectofinalwebII.WSArticulo.EditarRequest inValue = new proyectofinalwebII.WSArticulo.EditarRequest();
            inValue.Body = new proyectofinalwebII.WSArticulo.EditarRequestBody();
            inValue.Body.id = id;
            inValue.Body.nom = nom;
            inValue.Body.costo = costo;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Tipo = Tipo;
            return ((proyectofinalwebII.WSArticulo.WebService1Soap)(this)).EditarAsync(inValue);
        }
    }
}
